Zillow scrape
adnan-wahab/nyc-map pull request #15
Opened 2021-03-07 16:36 UTC by hmitrea

The code that I wrote has some issues and is not working fully, needs a bit of tweaking.

2021-03-09 14:04 UTC, adnan-wahab requested changes

2021-03-10 02:09 UTC, hmitrea commented on web_scraper/pageInfoData.js
> +let individualEl = []
Looking back at it, that variable was creating extra unnecessary space. 
We already have an array with all the urls from zillow.

2021-03-10 02:13 UTC, hmitrea commented on web_scraper/pageInfoData.js
> +    const url = individualEl.forEach((el) => el + 1)
Console logging it, I see that just headless chrome opens up but it's not going to the links to gather the data.

2021-03-10 02:18 UTC, hmitrea commented on web_scraper/pageInfoData.js
> +    const url = individualEl.forEach((el) => el + 1)
Yeah, I was not opening up the pages, the function getData was not getting called. Commented it out for now

2021-03-10 03:23 UTC, closed without merging